[2024-07-24T18:08:20.238+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:08:20.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:08:20.254+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T18:08:20.285+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T18:08:20.331+0000] {standard_task_runner.py:60} INFO - Started process 80 to run task
[2024-07-24T18:08:20.336+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpeftczad6']
[2024-07-24T18:08:20.371+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask film_category
[2024-07-24T18:08:20.718+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host b19a9c320dfd
[2024-07-24T18:08:21.197+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T18:08:21.219+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T18:08:22.691+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '(film_id,category_id)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 35, in execute
    StagingToDV().create_link().some_function(table, stage)
  File "/app/concretestage/StagingToDV.py", line 101, in some_function
    genaretedDF = generateSurogateKey(sourceDF, Code, list(SurogateKey.split(" ")),dest_col_list)
  File "/app/myFramework/utils/utils.py", line 55, in generateSurogateKey
    Surogatekey = newdf[key]+int(str(1000000) + str(code))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: '(film_id,category_id)'
[2024-07-24T18:08:22.721+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T180820, end_date=20240724T180822
[2024-07-24T18:08:22.745+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task film_category ('(film_id,category_id)'; 80)
[2024-07-24T18:08:22.774+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-24T18:08:22.801+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T18:10:28.331+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:10:28.355+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:10:28.373+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T18:10:28.416+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T18:10:28.447+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-24T18:10:28.456+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi_et61hs']
[2024-07-24T18:10:28.460+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask film_category
[2024-07-24T18:10:28.653+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 61620dbbe313
[2024-07-24T18:10:29.602+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T18:10:29.611+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T18:10:30.157+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '(film_id,category_id)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 35, in execute
    StagingToDV().create_link().some_function(table, stage)
  File "/app/concretestage/StagingToDV.py", line 101, in some_function
    genaretedDF = generateSurogateKey(sourceDF, Code, list(SurogateKey.split(" ")),dest_col_list)
  File "/app/myFramework/utils/utils.py", line 55, in generateSurogateKey
    Surogatekey = newdf[key]+int(str(1000000) + str(code))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: '(film_id,category_id)'
[2024-07-24T18:10:30.264+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T181028, end_date=20240724T181030
[2024-07-24T18:10:30.342+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task film_category ('(film_id,category_id)'; 89)
[2024-07-24T18:10:30.441+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-24T18:10:30.595+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T18:16:24.926+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:16:24.947+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:16:24.958+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T18:16:24.980+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T18:16:24.994+0000] {standard_task_runner.py:60} INFO - Started process 113 to run task
[2024-07-24T18:16:25.004+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_irg4eu_']
[2024-07-24T18:16:25.017+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask film_category
[2024-07-24T18:16:25.205+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 498c16fd9e64
[2024-07-24T18:16:26.318+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T18:16:26.330+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T18:16:26.428+0000] {logging_mixin.py:188} INFO - SurogateKey (film_id,category_id)
[2024-07-24T18:16:26.540+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '(film_id,category_id)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 35, in execute
    StagingToDV().create_link().some_function(table, stage)
  File "/app/concretestage/StagingToDV.py", line 102, in some_function
    genaretedDF = generateSurogateKey(sourceDF, Code, list(SurogateKey.split(" ")),dest_col_list)
  File "/app/myFramework/utils/utils.py", line 55, in generateSurogateKey
    Surogatekey = newdf[key]+int(str(1000000) + str(code))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: '(film_id,category_id)'
[2024-07-24T18:16:26.560+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T181624, end_date=20240724T181626
[2024-07-24T18:16:26.577+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task film_category ('(film_id,category_id)'; 113)
[2024-07-24T18:16:26.618+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-24T18:16:26.634+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T18:23:31.354+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:23:31.380+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:23:31.388+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T18:23:31.414+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T18:23:31.430+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-24T18:23:31.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjg2toofk']
[2024-07-24T18:23:31.478+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask film_category
[2024-07-24T18:23:31.668+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host bbd1d7010f8c
[2024-07-24T18:23:32.683+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T18:23:32.685+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T18:23:32.822+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T18:23:32.910+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T18:23:32.925+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T182331, end_date=20240724T182332
[2024-07-24T18:23:32.980+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T18:23:33.000+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T18:25:40.414+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:25:40.424+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T18:25:40.428+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T18:25:40.472+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T18:25:40.504+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-24T18:25:40.520+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp81j0mc2b']
[2024-07-24T18:25:40.540+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask film_category
[2024-07-24T18:25:40.694+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 5d8e7c9bb9aa
[2024-07-24T18:25:41.824+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T18:25:41.829+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T18:25:41.948+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T18:25:42.334+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T18:25:42.377+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T18:25:42.391+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T182540, end_date=20240724T182542
[2024-07-24T18:25:42.429+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T18:25:42.508+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T19:31:51.702+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T19:31:51.715+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T19:31:51.716+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T19:31:51.732+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T19:31:51.741+0000] {standard_task_runner.py:60} INFO - Started process 109 to run task
[2024-07-24T19:31:51.756+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg46kuzcq']
[2024-07-24T19:31:51.767+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask film_category
[2024-07-24T19:31:51.921+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 3e0bdef1d250
[2024-07-24T19:31:53.629+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T19:31:53.633+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T19:31:53.774+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T19:31:54.400+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T19:31:54.452+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T19:31:54.462+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T193151, end_date=20240724T193154
[2024-07-24T19:31:54.513+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T19:31:54.612+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T20:10:31.624+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:10:31.659+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:10:31.663+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T20:10:31.718+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T20:10:31.790+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmcoocvo7']
[2024-07-24T20:10:31.857+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask film_category
[2024-07-24T20:10:31.779+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-24T20:10:32.225+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 2b5a76a23048
[2024-07-24T20:10:33.534+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T20:10:33.537+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T20:10:33.687+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T20:10:33.945+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T20:10:33.993+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T20:10:34.002+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T201031, end_date=20240724T201034
[2024-07-24T20:10:34.072+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T20:10:34.090+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T20:12:42.513+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:12:42.665+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:12:42.678+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T20:12:42.987+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T20:12:43.048+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpg6ai4dh2']
[2024-07-24T20:12:43.055+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask film_category
[2024-07-24T20:12:43.041+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2024-07-24T20:12:43.349+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host c86ab2f6676c
[2024-07-24T20:12:45.728+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T20:12:45.737+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T20:12:45.970+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T20:12:46.779+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T20:12:46.858+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T20:12:46.871+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T201242, end_date=20240724T201246
[2024-07-24T20:12:46.960+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T20:12:47.011+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T20:14:52.951+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:14:52.982+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:14:52.985+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T20:14:53.091+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T20:14:53.131+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2024-07-24T20:14:53.133+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqhrbutlb']
[2024-07-24T20:14:53.153+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask film_category
[2024-07-24T20:14:53.220+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 86e5a5fada4c
[2024-07-24T20:14:53.949+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T20:14:53.963+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T20:14:54.063+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T20:14:55.065+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T20:14:55.144+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T20:14:55.183+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T201452, end_date=20240724T201455
[2024-07-24T20:14:55.249+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T20:14:55.280+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T20:23:46.417+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:23:46.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:23:46.454+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T20:23:46.502+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T20:23:46.527+0000] {standard_task_runner.py:60} INFO - Started process 148 to run task
[2024-07-24T20:23:46.532+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpup1tmhlr']
[2024-07-24T20:23:46.547+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask film_category
[2024-07-24T20:23:46.705+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host fd6805ab8e96
[2024-07-24T20:23:47.589+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T20:23:47.599+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T20:23:47.812+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T20:23:48.689+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T20:23:48.833+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T20:23:48.858+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T202346, end_date=20240724T202348
[2024-07-24T20:23:48.963+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T20:23:49.002+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T20:35:58.682+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:35:58.697+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-07-24T20:35:58.698+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-24T20:35:58.720+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): film_category> on 2024-07-23 00:00:00+00:00
[2024-07-24T20:35:58.744+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-24T20:35:58.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'film_category', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8_go0ew9']
[2024-07-24T20:35:58.847+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask film_category
[2024-07-24T20:35:59.157+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.film_category scheduled__2024-07-23T00:00:00+00:00 [running]> on host 7dd317f3ab25
[2024-07-24T20:36:00.392+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='film_category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T00:00:00+00:00'
[2024-07-24T20:36:00.417+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'film_category' and Stage = 'stagingtodv'
[2024-07-24T20:36:00.510+0000] {logging_mixin.py:188} INFO - SurogateKey film_id category_id
[2024-07-24T20:36:01.098+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbdv' and destschema='dvdrental' and desttablename='film_category';
[2024-07-24T20:36:01.131+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-24T20:36:01.142+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=stagingtodv, task_id=film_category, execution_date=20240723T000000, start_date=20240724T203558, end_date=20240724T203601
[2024-07-24T20:36:01.208+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-24T20:44:26.091+0000] {taskinstance.py:3318} INFO - Skipping mini scheduling run due to exception: SELECT dag_run.state AS dag_run_state, dag_run.id AS dag_run_id, dag_run.dag_id AS dag_run_dag_id, dag_run.queued_at AS dag_run_queued_at, dag_run.execution_date AS dag_run_execution_date, dag_run.start_date AS dag_run_start_date, dag_run.end_date AS dag_run_end_date, dag_run.run_id AS dag_run_run_id, dag_run.creating_job_id AS dag_run_creating_job_id, dag_run.external_trigger AS dag_run_external_trigger, dag_run.run_type AS dag_run_run_type, dag_run.conf AS dag_run_conf, dag_run.data_interval_start AS dag_run_data_interval_start, dag_run.data_interval_end AS dag_run_data_interval_end, dag_run.last_scheduling_decision AS dag_run_last_scheduling_decision, dag_run.dag_hash AS dag_run_dag_hash, dag_run.log_template_id AS dag_run_log_template_id, dag_run.updated_at AS dag_run_updated_at, dag_run.clear_number AS dag_run_clear_number 
FROM dag_run 
WHERE dag_run.dag_id = %(dag_id_1)s AND dag_run.run_id = %(run_id_1)s FOR UPDATE
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3267, in _schedule_downstream_tasks
    dag_run = with_row_locks(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2870, in one
    return self._iter().one()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[SQL: SELECT dag_run.state AS dag_run_state, dag_run.id AS dag_run_id, dag_run.dag_id AS dag_run_dag_id, dag_run.queued_at AS dag_run_queued_at, dag_run.execution_date AS dag_run_execution_date, dag_run.start_date AS dag_run_start_date, dag_run.end_date AS dag_run_end_date, dag_run.run_id AS dag_run_run_id, dag_run.creating_job_id AS dag_run_creating_job_id, dag_run.external_trigger AS dag_run_external_trigger, dag_run.run_type AS dag_run_run_type, dag_run.conf AS dag_run_conf, dag_run.data_interval_start AS dag_run_data_interval_start, dag_run.data_interval_end AS dag_run_data_interval_end, dag_run.last_scheduling_decision AS dag_run_last_scheduling_decision, dag_run.dag_hash AS dag_run_dag_hash, dag_run.log_template_id AS dag_run_log_template_id, dag_run.updated_at AS dag_run_updated_at, dag_run.clear_number AS dag_run_clear_number 
FROM dag_run 
WHERE dag_run.dag_id = %(dag_id_1)s AND dag_run.run_id = %(run_id_1)s FOR UPDATE]
[parameters: {'dag_id_1': 'stagingtodv', 'run_id_1': 'scheduled__2024-07-23T00:00:00+00:00'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
