[2024-07-22T20:46:23.693+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stagingtodv.rental manual__2024-07-22T20:46:21.507582+00:00 [queued]>
[2024-07-22T20:46:23.701+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stagingtodv.rental manual__2024-07-22T20:46:21.507582+00:00 [queued]>
[2024-07-22T20:46:23.708+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-22T20:46:23.742+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): rental> on 2024-07-22 20:46:21.507582+00:00
[2024-07-22T20:46:23.763+0000] {standard_task_runner.py:60} INFO - Started process 316 to run task
[2024-07-22T20:46:23.765+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stagingtodv', 'rental', 'manual__2024-07-22T20:46:21.507582+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7nzk6t5b']
[2024-07-22T20:46:23.771+0000] {standard_task_runner.py:88} INFO - Job 42: Subtask rental
[2024-07-22T20:46:23.859+0000] {task_command.py:423} INFO - Running <TaskInstance: stagingtodv.rental manual__2024-07-22T20:46:21.507582+00:00 [running]> on host ca612ea69d67
[2024-07-22T20:46:24.075+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stagingtodv' AIRFLOW_CTX_TASK_ID='rental' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T20:46:21.507582+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T20:46:21.507582+00:00'
[2024-07-22T20:46:24.083+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'rental' and Stage = 'stagingtodv'
[2024-07-22T20:46:24.941+0000] {logging_mixin.py:188} INFO - DFFFFFFFFFDFFFFFFFFF            0                   1  ...  5                   6
0          2 2005-05-24 22:54:33  ...  1 2006-02-16 02:30:53
1          3 2005-05-24 23:03:39  ...  1 2006-02-16 02:30:53
2          4 2005-05-24 23:04:41  ...  2 2006-02-16 02:30:53
3          5 2005-05-24 23:05:21  ...  1 2006-02-16 02:30:53
4          6 2005-05-24 23:08:07  ...  1 2006-02-16 02:30:53
...      ...                 ...  ... ..                 ...
16039  16046 2005-08-23 22:26:47  ...  2 2006-02-16 02:30:53
16040  16047 2005-08-23 22:42:48  ...  2 2006-02-16 02:30:53
16041  16048 2005-08-23 22:43:07  ...  1 2006-02-16 02:30:53
16042  16049 2005-08-23 22:50:12  ...  2 2006-02-16 02:30:53
16043      1 2005-05-24 22:53:30  ...  1 2006-02-15 21:30:53

[16044 rows x 7 columns]
[2024-07-22T20:46:24.980+0000] {logging_mixin.py:188} INFO - DFFFFFFFFFDFFFFFFFFF Empty DataFrame
Columns: []
Index: []
[2024-07-22T20:46:24.980+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 33, in execute
    StagingToDV().create_incremental().some_function(table, stage)
  File "/app/concretestage/StagingToDV.py", line 64, in some_function
    dest_col_list = getDF(DestDBName, DestTableName,DestSchema).columns()
  File "/app/myFramework/utils/utils.py", line 32, in getDF
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 8 elements
[2024-07-22T20:46:24.992+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=stagingtodv, task_id=rental, execution_date=20240722T204621, start_date=20240722T204623, end_date=20240722T204624
[2024-07-22T20:46:25.005+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 42 for task rental (Length mismatch: Expected axis has 0 elements, new values have 8 elements; 316)
[2024-07-22T20:46:25.025+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-22T20:46:25.037+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
