[2024-07-10T19:19:12.815+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.844+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:19:12.847+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:19:12.893+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:19:12.909+0000] {standard_task_runner.py:60} INFO - Started process 98 to run task
[2024-07-10T19:19:12.944+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmploembnqr']
[2024-07-10T19:19:12.960+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask category
[2024-07-10T19:19:13.128+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 988357c0810b
[2024-07-10T19:19:14.604+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:19:14.610+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'SqlToStaging'
[2024-07-10T19:19:14.647+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 30, in get_data_from_conf_table
    cur.execute(query)
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
[2024-07-10T19:19:14.680+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=category, execution_date=20240709T000000, start_date=20240710T191912, end_date=20240710T191914
[2024-07-10T19:19:14.715+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task category ('psycopg2.extensions.connection' object has no attribute 'execute'; 98)
[2024-07-10T19:19:14.759+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:19:14.834+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:24:52.140+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.158+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:24:52.161+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:24:52.180+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:24:52.195+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T19:24:52.224+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl65hglqc']
[2024-07-10T19:24:52.248+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask category
[2024-07-10T19:24:52.488+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 1dd842c603c2
[2024-07-10T19:24:53.649+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:24:53.656+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'SqlToStaging'
[2024-07-10T19:24:53.674+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)['tabletype'].values[0]
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:24:53.683+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=category, execution_date=20240709T000000, start_date=20240710T192452, end_date=20240710T192453
[2024-07-10T19:24:53.708+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task category (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 96)
[2024-07-10T19:24:53.749+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:24:53.823+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:33:52.721+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.743+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:33:52.746+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:33:52.795+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:33:52.808+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-10T19:33:52.830+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'SqlToStaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3nyffogq']
[2024-07-10T19:33:52.862+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask category
[2024-07-10T19:33:53.008+0000] {task_command.py:423} INFO - Running <TaskInstance: SqlToStaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:33:54.283+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='SqlToStaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:33:54.287+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'SqlToStaging'
[2024-07-10T19:33:54.339+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 41, in process_table
    tabletype = get_data_from_conf_table(table,stage)
  File "/opt/airflow/dags/dag.py", line 34, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-10T19:33:54.394+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=SqlToStaging, task_id=category, execution_date=20240709T000000, start_date=20240710T193352, end_date=20240710T193354
[2024-07-10T19:33:54.412+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task category (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 96)
[2024-07-10T19:33:54.490+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T19:33:54.535+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:37:48.121+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.155+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:37:48.165+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:37:48.205+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:37:48.220+0000] {standard_task_runner.py:60} INFO - Started process 239 to run task
[2024-07-10T19:37:48.240+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgpmvuet8']
[2024-07-10T19:37:48.255+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask category
[2024-07-10T19:37:48.428+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a0982d156a38
[2024-07-10T19:37:48.647+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:37:48.649+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T19:37:49.642+0000] {logging_mixin.py:188} INFO -    0         1          2       3     4   ...    10    11    12            13    14
0   2  category  dvdrental  public  full  ...  None  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:37:49.665+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T19:37:49.674+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:37:49.682+0000] {logging_mixin.py:188} INFO - table: category
[2024-07-10T19:37:49.687+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:category
[2024-07-10T19:37:49.689+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:37:49.705+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T193748, end_date=20240710T193749
[2024-07-10T19:37:49.758+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:37:49.784+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:39:58.147+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.161+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:39:58.162+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:39:58.197+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:39:58.203+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-10T19:39:58.216+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpl47hnk9i']
[2024-07-10T19:39:58.226+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask category
[2024-07-10T19:39:58.361+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 4118dead3d7f
[2024-07-10T19:39:59.844+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:39:59.848+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T19:39:59.903+0000] {logging_mixin.py:188} INFO -    0         1          2       3     4   ...    10    11    12            13    14
0   2  category  dvdrental  public  full  ...  None  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:39:59.904+0000] {logging_mixin.py:188} INFO - full
[2024-07-10T19:39:59.906+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:39:59.906+0000] {logging_mixin.py:188} INFO - table: category
[2024-07-10T19:39:59.907+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:category
[2024-07-10T19:39:59.909+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:39:59.929+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T193958, end_date=20240710T193959
[2024-07-10T19:39:59.953+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:40:00.006+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:44:02.961+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:02.978+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:44:02.979+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:44:03.009+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:44:03.021+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-10T19:44:03.034+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpd6lse_df']
[2024-07-10T19:44:03.045+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask category
[2024-07-10T19:44:03.320+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host a383c1e8c871
[2024-07-10T19:44:04.297+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:44:04.312+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T19:44:04.559+0000] {logging_mixin.py:188} INFO -    0         1          2       3     4   ...    10    11    12            13    14
0   2  category  dvdrental  public  full  ...  None  None  None  sqltostaging  None

[1 rows x 15 columns]
[2024-07-10T19:44:04.611+0000] {logging_mixin.py:188} INFO - full
[2024-07-10T19:44:04.620+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-10T19:44:04.629+0000] {logging_mixin.py:188} INFO - table: category
[2024-07-10T19:44:04.630+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:category
[2024-07-10T19:44:04.635+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:44:04.667+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T194402, end_date=20240710T194404
[2024-07-10T19:44:04.741+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:44:04.875+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:53:56.989+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:57.006+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:53:57.012+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:53:57.036+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:53:57.049+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-10T19:53:57.061+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnplojcvf']
[2024-07-10T19:53:57.077+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask category
[2024-07-10T19:53:57.242+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c340805483c7
[2024-07-10T19:53:58.186+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:53:58.220+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:53:58.259+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T195356, end_date=20240710T195358
[2024-07-10T19:53:58.332+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:53:58.390+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T19:56:46.687+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.714+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T19:56:46.721+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T19:56:46.774+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T19:56:46.790+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2024-07-10T19:56:46.822+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxzuyh5h0']
[2024-07-10T19:56:46.837+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask category
[2024-07-10T19:56:47.007+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host eb5f087f7265
[2024-07-10T19:56:48.148+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T19:56:48.197+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-10T19:56:48.208+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T195646, end_date=20240710T195648
[2024-07-10T19:56:48.260+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-10T19:56:48.319+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:00:56.613+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.701+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:00:56.703+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:00:56.739+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:00:56.756+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-10T20:00:56.813+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxktr8mf6']
[2024-07-10T20:00:56.832+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask category
[2024-07-10T20:00:57.069+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c8649e4aae44
[2024-07-10T20:01:01.288+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:01:01.435+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:01:01.514+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:01:01.520+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:01:01.577+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T200056, end_date=20240710T200101
[2024-07-10T20:01:01.632+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 95)
[2024-07-10T20:01:01.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:01:02.034+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:05:21.241+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.255+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:05:21.263+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:05:21.292+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:05:21.304+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-10T20:05:21.319+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp6qo6gha6']
[2024-07-10T20:05:21.331+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask category
[2024-07-10T20:05:21.472+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 3f026d601c5c
[2024-07-10T20:05:22.194+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:05:22.373+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:05:22.498+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:05:22.524+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:05:22.577+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T200521, end_date=20240710T200522
[2024-07-10T20:05:22.599+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 99)
[2024-07-10T20:05:22.654+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:05:22.718+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:09:18.571+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.629+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:09:18.706+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:09:18.767+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:09:18.780+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-07-10T20:09:18.787+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpid6qzd4p']
[2024-07-10T20:09:18.790+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask category
[2024-07-10T20:09:19.093+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 61a58fe9b448
[2024-07-10T20:09:19.418+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:09:20.353+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:09:20.400+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:09:20.406+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:09:20.426+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T200918, end_date=20240710T200920
[2024-07-10T20:09:20.438+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 102)
[2024-07-10T20:09:20.480+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:09:20.526+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:15:06.633+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.649+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:15:06.651+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:15:06.683+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:15:06.698+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-07-10T20:15:06.705+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjche0pzq']
[2024-07-10T20:15:06.715+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask category
[2024-07-10T20:15:06.858+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host c782b552e7b5
[2024-07-10T20:15:08.311+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:15:08.374+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:15:08.466+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:15:08.467+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:15:08.484+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T201506, end_date=20240710T201508
[2024-07-10T20:15:08.527+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 94)
[2024-07-10T20:15:08.554+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:15:08.639+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:19:53.528+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.562+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:19:53.566+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:19:53.626+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:19:53.656+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-10T20:19:53.667+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5eemk1oy']
[2024-07-10T20:19:53.686+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask category
[2024-07-10T20:19:53.835+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host dcd5a91c9a96
[2024-07-10T20:19:54.931+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:19:54.991+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:19:55.056+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:19:55.057+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:19:55.085+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T201953, end_date=20240710T201955
[2024-07-10T20:19:55.103+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 97)
[2024-07-10T20:19:55.124+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:19:55.142+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:25:52.157+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.174+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:25:52.182+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:25:52.248+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:25:52.261+0000] {standard_task_runner.py:60} INFO - Started process 130 to run task
[2024-07-10T20:25:52.277+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3swdeb5j']
[2024-07-10T20:25:52.324+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask category
[2024-07-10T20:25:52.534+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host d72f5bf26a9d
[2024-07-10T20:25:53.748+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:25:53.850+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:25:53.905+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:25:53.906+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:25:53.921+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T202552, end_date=20240710T202553
[2024-07-10T20:25:53.941+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 130)
[2024-07-10T20:25:53.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:25:54.022+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:33:41.760+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.778+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:33:41.780+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:33:41.810+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:33:41.837+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2024-07-10T20:33:41.846+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_dtksiny']
[2024-07-10T20:33:41.875+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask category
[2024-07-10T20:33:42.033+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host d0a0151057b2
[2024-07-10T20:33:42.657+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:33:43.191+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:33:43.328+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:33:43.341+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:33:43.379+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T203341, end_date=20240710T203343
[2024-07-10T20:33:43.408+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 89)
[2024-07-10T20:33:43.420+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:33:43.455+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:36:57.452+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.488+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:36:57.498+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:36:57.543+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:36:57.553+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-10T20:36:57.567+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_yc_oss6']
[2024-07-10T20:36:57.589+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask category
[2024-07-10T20:36:57.794+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host dca83dd4e715
[2024-07-10T20:36:59.097+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:36:59.213+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:36:59.422+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:36:59.426+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:36:59.452+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T203657, end_date=20240710T203659
[2024-07-10T20:36:59.590+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 93)
[2024-07-10T20:36:59.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:36:59.703+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T20:40:14.110+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:14.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [queued]>
[2024-07-10T20:40:14.140+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-10T20:40:14.163+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): category> on 2024-07-09 00:00:00+00:00
[2024-07-10T20:40:14.203+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2024-07-10T20:40:14.231+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'category', 'scheduled__2024-07-09T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7tkiyw40']
[2024-07-10T20:40:14.245+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask category
[2024-07-10T20:40:14.382+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.category scheduled__2024-07-09T00:00:00+00:00 [running]> on host 2bc01acfbd3e
[2024-07-10T20:40:15.167+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='category' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-09T00:00:00+00:00'
[2024-07-10T20:40:15.237+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'category' and Stage = 'sqltostaging'
[2024-07-10T20:40:15.372+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   2        category    dvdrental  ...  None  sqltostaging          None

[1 rows x 15 columns]
[2024-07-10T20:40:15.377+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 44, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
TypeError: getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'
[2024-07-10T20:40:15.423+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=category, execution_date=20240709T000000, start_date=20240710T204014, end_date=20240710T204015
[2024-07-10T20:40:15.434+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task category (getDF() missing 3 required positional arguments: 'filterColumn', 'dateFrom', and 'dateTo'; 103)
[2024-07-10T20:40:15.500+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-10T20:40:15.554+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
