[2024-07-02T18:42:24.438+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:42:24.456+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:42:24.462+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T18:42:24.528+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T18:42:24.547+0000] {standard_task_runner.py:60} INFO - Started process 102 to run task
[2024-07-02T18:42:24.562+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5p56_a1b']
[2024-07-02T18:42:24.573+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask store
[2024-07-02T18:42:24.753+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 5b7251376729
[2024-07-02T18:42:26.109+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T18:42:26.112+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: process_table() missing 1 required positional argument: 'table_type'
[2024-07-02T18:42:26.128+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T184224, end_date=20240702T184226
[2024-07-02T18:42:26.166+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task store (process_table() missing 1 required positional argument: 'table_type'; 102)
[2024-07-02T18:42:26.214+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T18:42:26.228+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T18:50:28.375+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:50:28.403+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T18:50:28.418+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T18:50:28.459+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T18:50:28.472+0000] {standard_task_runner.py:60} INFO - Started process 97 to run task
[2024-07-02T18:50:28.486+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpklr169xv']
[2024-07-02T18:50:28.499+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask store
[2024-07-02T18:50:28.644+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host e236fd1115af
[2024-07-02T18:50:29.766+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T18:50:29.767+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T18:50:29.768+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T18:50:29.770+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T18:50:29.979+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T18:50:29.985+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T185028, end_date=20240702T185029
[2024-07-02T18:50:30.040+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T18:50:30.066+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:20:13.063+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:20:13.090+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:20:13.093+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:20:13.133+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:20:13.147+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-07-02T20:20:13.170+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpixtw2_e8']
[2024-07-02T20:20:13.185+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask store
[2024-07-02T20:20:13.375+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 881b4526a2de
[2024-07-02T20:20:14.459+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:20:14.471+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:20:14.480+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:20:14.484+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:20:14.526+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 29, in some_function
    print(get_data_from_conf_table("staff", "SqlToStaging"))
  File "/app/myFramework/utils/utils.py", line 137, in get_data_from_conf_table
    cur = conn.getCursor("Postgres")
  File "/app/myFramework/source/posgresql/connect.py", line 6, in getCursor
    conn = psycopg2.connect(database = dbname,
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (172.20.0.3), port 9999 failed: FATAL:  database "Postgres" does not exist

[2024-07-02T20:20:14.586+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T202013, end_date=20240702T202014
[2024-07-02T20:20:14.670+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task store (connection to server at "postgres_db" (172.20.0.3), port 9999 failed: FATAL:  database "Postgres" does not exist
; 94)
[2024-07-02T20:20:14.850+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:20:14.963+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:22:14.170+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:22:14.189+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:22:14.194+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:22:14.213+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:22:14.223+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-02T20:22:14.240+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpub408jfw']
[2024-07-02T20:22:14.257+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask store
[2024-07-02T20:22:14.443+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host b2ca66e4d1f6
[2024-07-02T20:22:15.328+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:22:15.428+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:22:15.430+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:22:15.432+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:22:16.044+0000] {logging_mixin.py:188} INFO -    0      1          2       3     4   ...    10    11    12            13    14
0   9  staff  dvdrental  public  full  ...  None  None  None  SqlToStaging  None

[1 rows x 15 columns]
[2024-07-02T20:22:16.065+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:22:16.098+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T202214, end_date=20240702T202216
[2024-07-02T20:22:16.172+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:22:16.259+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:25:37.606+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:25:37.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:25:37.666+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:25:37.720+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:25:37.731+0000] {standard_task_runner.py:60} INFO - Started process 93 to run task
[2024-07-02T20:25:37.746+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp200hszdh']
[2024-07-02T20:25:37.756+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask store
[2024-07-02T20:25:37.947+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host e847a37dafab
[2024-07-02T20:25:39.095+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:25:39.098+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:25:39.105+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:25:39.109+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:25:39.298+0000] {logging_mixin.py:188} INFO - <class 'pandas.core.frame.DataFrame'>
[2024-07-02T20:25:39.342+0000] {logging_mixin.py:188} INFO -    id sourcetablename sourcedbname  ...  code         stage last_run_date
0   9           staff    dvdrental  ...  None  SqlToStaging          None

[1 rows x 15 columns]
[2024-07-02T20:25:39.347+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:25:39.376+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T202537, end_date=20240702T202539
[2024-07-02T20:25:39.444+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:25:39.513+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:33:53.754+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:33:53.798+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:33:53.798+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:33:53.831+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:33:53.839+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-07-02T20:33:53.843+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5o4s_pyl']
[2024-07-02T20:33:53.869+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask store
[2024-07-02T20:33:54.241+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 99fbc1087931
[2024-07-02T20:33:54.547+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:33:54.550+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:33:54.552+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:33:54.554+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:33:55.408+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SourceDBName'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    print(f"{df['SourceDBName']} \n {df['SourceTableName']} \n {df['SourceSchema']}")
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'SourceDBName'
[2024-07-02T20:33:55.423+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T203353, end_date=20240702T203355
[2024-07-02T20:33:55.442+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 15 for task store ('SourceDBName'; 99)
[2024-07-02T20:33:55.490+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:33:55.511+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:36:07.767+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:36:07.784+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:36:07.791+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:36:07.840+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:36:07.854+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-02T20:36:07.861+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7jktplit']
[2024-07-02T20:36:07.875+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask store
[2024-07-02T20:36:08.037+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 8ef3b2afa95a
[2024-07-02T20:36:09.218+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:36:09.219+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:36:09.220+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:36:09.221+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:36:09.257+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-02T20:36:09.258+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:36:09.273+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T203607, end_date=20240702T203609
[2024-07-02T20:36:09.324+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:36:09.339+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:40:31.069+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:40:31.078+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:40:31.079+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:40:31.096+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:40:31.105+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-02T20:40:31.126+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp508eddlb']
[2024-07-02T20:40:31.140+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask store
[2024-07-02T20:40:31.352+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host f7a45131ad00
[2024-07-02T20:40:32.492+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:40:32.499+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:40:32.517+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:40:32.519+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:40:32.663+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage, "FULL","public")
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, type, schema, table)
  File "/app/concretestage/SQLToStaging.py", line 29, in some_function
    df = get_data_from_conf_table(table, stage)
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-02T20:40:32.703+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T204031, end_date=20240702T204032
[2024-07-02T20:40:32.719+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task store (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 88)
[2024-07-02T20:40:32.814+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:40:32.878+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:44:45.093+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:44:45.105+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:44:45.109+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:44:45.126+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:44:45.149+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-07-02T20:44:45.172+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkc_z_2ng']
[2024-07-02T20:44:45.189+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask store
[2024-07-02T20:44:45.376+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 28c1247628aa
[2024-07-02T20:44:46.237+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:44:46.239+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:44:46.240+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:44:46.244+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 type: FULL 
 schema: public 
 table:store
[2024-07-02T20:44:46.254+0000] {logging_mixin.py:188} INFO - sqltostaging store
[2024-07-02T20:44:46.266+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:44:46.288+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T204445, end_date=20240702T204446
[2024-07-02T20:44:46.381+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:44:46.490+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:47:20.460+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:47:20.524+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:47:20.527+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:47:20.595+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:47:20.614+0000] {standard_task_runner.py:60} INFO - Started process 88 to run task
[2024-07-02T20:47:20.619+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsqallk9r']
[2024-07-02T20:47:20.635+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask store
[2024-07-02T20:47:20.800+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 0dbf5a897656
[2024-07-02T20:47:22.007+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:47:22.031+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:47:22.032+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:47:22.033+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
TypeError: execute() missing 2 required positional arguments: 'type' and 'schema'
[2024-07-02T20:47:22.069+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T204720, end_date=20240702T204722
[2024-07-02T20:47:22.098+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task store (execute() missing 2 required positional arguments: 'type' and 'schema'; 88)
[2024-07-02T20:47:22.150+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:47:22.401+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:49:58.214+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:49:58.239+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:49:58.241+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:49:58.326+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:49:58.344+0000] {standard_task_runner.py:60} INFO - Started process 95 to run task
[2024-07-02T20:49:58.350+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpd1vk2iw1']
[2024-07-02T20:49:58.359+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask store
[2024-07-02T20:49:58.489+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 82e116e15bed
[2024-07-02T20:49:59.582+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:49:59.589+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:49:59.601+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:49:59.605+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:store
[2024-07-02T20:49:59.607+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
TypeError: some_function() missing 2 required positional arguments: 'schema' and 'table'
[2024-07-02T20:49:59.656+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T204958, end_date=20240702T204959
[2024-07-02T20:49:59.784+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task store (some_function() missing 2 required positional arguments: 'schema' and 'table'; 95)
[2024-07-02T20:49:59.839+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:49:59.877+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:51:50.799+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:51:50.878+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:51:50.882+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:51:50.979+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:51:51.019+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-07-02T20:51:51.095+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp91du3ou1']
[2024-07-02T20:51:51.121+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask store
[2024-07-02T20:51:51.436+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host 910796d1882f
[2024-07-02T20:51:52.249+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:51:52.263+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:51:52.271+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:51:52.297+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:store
[2024-07-02T20:51:52.408+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 22, in process_table
    return  execute(table, stage)
  File "/app/main.py", line 25, in execute
    SqlToStaging().create_full().some_function(stage, table)
  File "/app/concretestage/SQLToStaging.py", line 30, in some_function
    df = get_data_from_conf_table(table, stage)
  File "/app/myFramework/utils/utils.py", line 142, in get_data_from_conf_table
    df.columns = [desc[0] for desc in cur.description]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 15 elements
[2024-07-02T20:51:52.465+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T205150, end_date=20240702T205152
[2024-07-02T20:51:52.504+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task store (Length mismatch: Expected axis has 0 elements, new values have 15 elements; 92)
[2024-07-02T20:51:52.562+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-02T20:51:52.642+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T20:54:17.516+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:54:17.549+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [queued]>
[2024-07-02T20:54:17.552+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-02T20:54:17.579+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): store> on 2024-07-01 00:00:00+00:00
[2024-07-02T20:54:17.604+0000] {standard_task_runner.py:60} INFO - Started process 96 to run task
[2024-07-02T20:54:17.608+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'store', 'scheduled__2024-07-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpdxtn51ub']
[2024-07-02T20:54:17.622+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask store
[2024-07-02T20:54:17.778+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.store scheduled__2024-07-01T00:00:00+00:00 [running]> on host df9727a9ba29
[2024-07-02T20:54:18.427+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='store' AIRFLOW_CTX_EXECUTION_DATE='2024-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-01T00:00:00+00:00'
[2024-07-02T20:54:18.429+0000] {logging_mixin.py:188} INFO - dvtobv :dag_id
[2024-07-02T20:54:18.430+0000] {logging_mixin.py:188} INFO - table: store
[2024-07-02T20:54:18.431+0000] {logging_mixin.py:188} INFO - 
 stage: sqltostaging 
 table:store
[2024-07-02T20:54:18.512+0000] {logging_mixin.py:188} INFO - 0    dvdrental
Name: sourcedbname, dtype: object 
 0    staff
Name: sourcetablename, dtype: object 
 0    public
Name: sourceschema, dtype: object
[2024-07-02T20:54:18.513+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-02T20:54:18.530+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=store, execution_date=20240701T000000, start_date=20240702T205417, end_date=20240702T205418
[2024-07-02T20:54:18.627+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-02T20:54:18.664+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
