[2024-07-16T16:34:40.150+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T16:34:40.182+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T16:34:40.191+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T16:34:40.232+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T16:34:40.262+0000] {standard_task_runner.py:60} INFO - Started process 130 to run task
[2024-07-16T16:34:40.281+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_666dl4u']
[2024-07-16T16:34:40.284+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask country
[2024-07-16T16:34:40.377+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host f77c41d1d1e9
[2024-07-16T16:34:41.026+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T16:34:41.093+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T16:34:41.191+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 16:34:38.158793

[1 rows x 15 columns]
[2024-07-16T16:34:41.542+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='DBStaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T16:34:41.594+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T16:34:41.624+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T163440, end_date=20240716T163441
[2024-07-16T16:34:41.686+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T16:34:41.710+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T17:43:02.513+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T17:43:02.530+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T17:43:02.542+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T17:43:02.582+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T17:43:02.593+0000] {standard_task_runner.py:60} INFO - Started process 247 to run task
[2024-07-16T17:43:02.601+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwke_ddh3']
[2024-07-16T17:43:02.609+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask country
[2024-07-16T17:43:02.823+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host e1ba87a2fe19
[2024-07-16T17:43:02.997+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T17:43:03.018+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T17:43:03.081+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T17:43:03.713+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 16:34:41.588109

[1 rows x 15 columns]
[2024-07-16T17:43:03.985+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='DBStaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T17:43:04.002+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T17:43:04.013+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T174302, end_date=20240716T174304
[2024-07-16T17:43:04.035+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T17:43:04.050+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:37:57.440+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:37:57.451+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:37:57.453+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:37:57.506+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:37:57.533+0000] {standard_task_runner.py:60} INFO - Started process 259 to run task
[2024-07-16T18:37:57.560+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_4pn0e79']
[2024-07-16T18:37:57.570+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask country
[2024-07-16T18:37:57.791+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host b7021158e377
[2024-07-16T18:37:58.062+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:37:58.067+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:37:58.157+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:37:59.388+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 17:43:03.997646

[1 rows x 15 columns]
[2024-07-16T18:37:59.483+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 38, in some_function
    sourceDF = getDF(sourcedbname,sourcetablename , sourceschema)
  File "/app/myFramework/utils/utils.py", line 29, in getDF
    cur.execute(query)
psycopg2.errors.FeatureNotSupported: cross-database references are not implemented: "dbstaging.public.dada"
LINE 1: select T.* from dbstaging.public.dada T
                        ^

[2024-07-16T18:37:59.554+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T183757, end_date=20240716T183759
[2024-07-16T18:37:59.663+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task country (cross-database references are not implemented: "dbstaging.public.dada"
LINE 1: select T.* from dbstaging.public.dada T
                        ^
; 259)
[2024-07-16T18:37:59.825+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T18:38:00.118+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:39:44.461+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:39:44.491+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:39:44.492+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:39:44.546+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:39:44.587+0000] {standard_task_runner.py:60} INFO - Started process 101 to run task
[2024-07-16T18:39:44.597+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpluzgwmjb']
[2024-07-16T18:39:44.623+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask country
[2024-07-16T18:39:44.783+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host 7465d1ceecf3
[2024-07-16T18:39:46.532+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:39:46.544+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:39:46.614+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:39:46.692+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 17:43:03.997646

[1 rows x 15 columns]
[2024-07-16T18:39:46.757+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres_db" (172.31.0.4), port 9999 failed: FATAL:  database "DBStaging" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 45, in process_table
    return  execute(table, stage, tabletype)
  File "/app/main.py", line 26, in execute
    SqlToStaging().create_full().some_function(table, stage)
  File "/app/concretestage/SQLToStaging.py", line 40, in some_function
    fillPosgres(sourceDF, DestDBName, DestSchema, DestTableName, InsertionType)
  File "/app/myFramework/utils/utils.py", line 36, in fillPosgres
    df.to_sql(tablename, conn.getEngine(dst_dbname)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 768, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1539, in __init__
    con = self.exit_stack.enter_context(con.connect())
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres_db" (172.31.0.4), port 9999 failed: FATAL:  database "DBStaging" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-16T18:39:46.801+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T183944, end_date=20240716T183946
[2024-07-16T18:39:46.835+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task country ((psycopg2.OperationalError) connection to server at "postgres_db" (172.31.0.4), port 9999 failed: FATAL:  database "DBStaging" does not exist

(Background on this error at: https://sqlalche.me/e/14/e3q8); 101)
[2024-07-16T18:39:46.889+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T18:39:46.942+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:45:08.209+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:45:08.277+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:45:08.280+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:45:08.302+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:45:08.321+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-07-16T18:45:08.365+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpagyvfx0t']
[2024-07-16T18:45:08.378+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask country
[2024-07-16T18:45:08.602+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host 2e3dbb9eb862
[2024-07-16T18:45:10.586+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:45:10.602+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:45:10.810+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:45:11.491+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 17:43:03.997646

[1 rows x 15 columns]
[2024-07-16T18:45:12.550+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbstaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T18:45:12.682+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T18:45:12.739+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T184508, end_date=20240716T184512
[2024-07-16T18:45:12.905+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T18:45:13.210+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:51:27.398+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:51:27.413+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:51:27.421+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:51:27.454+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:51:27.470+0000] {standard_task_runner.py:60} INFO - Started process 154 to run task
[2024-07-16T18:51:27.476+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphgzkvocy']
[2024-07-16T18:51:27.509+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask country
[2024-07-16T18:51:27.744+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host 7844bece6866
[2024-07-16T18:51:29.565+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:51:29.570+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:51:29.597+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:51:29.693+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 18:45:12.643213

[1 rows x 15 columns]
[2024-07-16T18:51:29.893+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbstaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T18:51:29.930+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T18:51:29.949+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T185127, end_date=20240716T185129
[2024-07-16T18:51:29.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T18:51:29.997+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:53:08.852+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:53:08.877+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:53:08.879+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:53:08.898+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:53:08.902+0000] {standard_task_runner.py:60} INFO - Started process 81 to run task
[2024-07-16T18:53:08.909+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpde6oqe1u']
[2024-07-16T18:53:08.914+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask country
[2024-07-16T18:53:09.117+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host 6ef7a8da30c0
[2024-07-16T18:53:10.690+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:53:10.700+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:53:10.958+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:53:11.094+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 18:51:29.923520

[1 rows x 15 columns]
[2024-07-16T18:53:11.821+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbstaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T18:53:11.864+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T18:53:11.873+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T185308, end_date=20240716T185311
[2024-07-16T18:53:11.932+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T18:53:12.032+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T18:56:02.280+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:56:02.317+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [queued]>
[2024-07-16T18:56:02.335+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-16T18:56:02.492+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): country> on 2024-07-15 00:00:00+00:00
[2024-07-16T18:56:02.527+0000] {standard_task_runner.py:60} INFO - Started process 91 to run task
[2024-07-16T18:56:02.580+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sqltostaging', 'country', 'scheduled__2024-07-15T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkxiye2p6']
[2024-07-16T18:56:02.631+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask country
[2024-07-16T18:56:02.983+0000] {task_command.py:423} INFO - Running <TaskInstance: sqltostaging.country scheduled__2024-07-15T00:00:00+00:00 [running]> on host 1733eeb0def3
[2024-07-16T18:56:07.575+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sqltostaging' AIRFLOW_CTX_TASK_ID='country' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-15T00:00:00+00:00'
[2024-07-16T18:56:07.608+0000] {logging_mixin.py:188} INFO - -------------------------------------------- select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:56:08.057+0000] {logging_mixin.py:188} INFO - select *  from etlconf.Etl_Process_Mapping where SourceTableName = 'country' and Stage = 'sqltostaging'
[2024-07-16T18:56:08.484+0000] {logging_mixin.py:188} INFO -    id sourcetablename  ...         stage              last_run_date
0   6         country  ...  sqltostaging 2024-07-16 18:53:11.854175

[1 rows x 15 columns]
[2024-07-16T18:56:09.368+0000] {logging_mixin.py:188} INFO - update etlconf.Etl_Process_Mapping T set last_run_date = current_timestamp where destdbname='dbstaging' and destschema='dvdrental' and desttablename='country';
[2024-07-16T18:56:09.621+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-07-16T18:56:09.705+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=sqltostaging, task_id=country, execution_date=20240715T000000, start_date=20240716T185602, end_date=20240716T185609
[2024-07-16T18:56:09.894+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-07-16T18:56:10.211+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
